USE `Hopper-4313773-aurelio-capingana`;
SET SQL_SAFE_UPDATES = 0;

CREATE TABLE Open_Time_Pojects(
id VARCHAR(255) PRIMARY KEY,
nome VARCHAR(255) UNIQUE NOT NULL,
titulo VARCHAR(255) NOT NULL,
data DATE NOT NULL);

SELECT * FROM Open_Time_Pojects